from PyQt5 import QtCore, QtGui, QtWidgets
import os
import requests
import json
import sys
from datetime import datetime


#from main import get_forecast

API_KEY = '05a59ce96cb307a4e12ed503a455c1a0' #API Key for forcast calls


#----------------------(Start) Downloaded Images----------------------------
sunImage = f'{os.getcwd()}\\images\\sun.png'
percipImage = f'{os.getcwd()}\\images\\water.png'
backgroundImage = f'{os.getcwd()}\\images\\clouds.png'
#----------------------(End) Downloaded Images------------------------------

stateList = [ 'AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA',
           'HI', 'IA', 'ID', 'IL', 'IN', 'KS', 'KY', 'LA', 'MA', 'MD', 'ME',
           'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH', 'NJ', 'NM',
           'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX',
           'UT', 'VA', 'VT', 'WA', 'WI', 'WV', 'WY']


class Ui_MainWindow(object): #houses all of the functions/UI for the application
        
        #-------------------------------------(Start) Code to generate UI------------------------------------------
        def setupUi(self, MainWindow):
                MainWindow.setObjectName("MainWindow")
                MainWindow.resize(898, 564)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
                MainWindow.setSizePolicy(sizePolicy)
                MainWindow.setMinimumSize(QtCore.QSize(898, 564))
                MainWindow.setMaximumSize(QtCore.QSize(898, 564))
                palette = QtGui.QPalette()
                brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
                brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
                brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
                brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
                brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
                brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
                brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
                brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
                brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
                brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
                brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
                brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
                brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
                brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
                brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
                brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
                brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
                brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
                brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
                brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
                brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
                brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
                brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
                brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
                brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
                brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
                brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
                brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
                brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
                brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
                brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
                brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
                brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
                brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
                brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
                brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
                brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
                brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
                brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
                brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
                brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
                brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
                brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
                brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
                brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
                MainWindow.setPalette(palette)
                font = QtGui.QFont()
                font.setFamily("MS Shell Dlg 2")
                font.setBold(True)
                font.setWeight(75)
                MainWindow.setFont(font)
                MainWindow.setTabShape(QtWidgets.QTabWidget.Triangular)
                self.centralwidget = QtWidgets.QWidget(MainWindow)
                self.centralwidget.setObjectName("centralwidget")
                self.TitleLabel = QtWidgets.QLabel(self.centralwidget)
                self.TitleLabel.setGeometry(QtCore.QRect(20, 0, 321, 161))
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.TitleLabel.sizePolicy().hasHeightForWidth())
                self.TitleLabel.setSizePolicy(sizePolicy)
                palette = QtGui.QPalette()
                brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
                brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
                brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
                brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
                brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
                brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
                brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
                brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
                brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
                brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
                brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
                brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
                brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
                brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
                brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
                brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
                brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
                brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
                brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
                brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
                brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
                brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
                brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
                brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
                brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
                brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
                brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
                brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
                brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
                brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
                brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
                brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
                brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
                brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
                brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
                brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
                brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
                brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
                brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
                brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
                brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
                brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
                brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
                brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
                brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
                self.TitleLabel.setPalette(palette)
                font = QtGui.QFont()
                font.setFamily("qtquickcontrols")
                font.setPointSize(45)
                font.setBold(True)
                font.setWeight(75)
                font.setStrikeOut(False)
                font.setKerning(True)
                self.TitleLabel.setFont(font)
                self.TitleLabel.setObjectName("TitleLabel")
                self.backgroundImageLabel = QtWidgets.QLabel(self.centralwidget)
                self.backgroundImageLabel.setGeometry(QtCore.QRect(-10, -30, 921, 611))
                font = QtGui.QFont()
                font.setFamily("MV Boli")
                self.backgroundImageLabel.setFont(font)
                self.backgroundImageLabel.setText("")
                self.backgroundImageLabel.setPixmap(QtGui.QPixmap(backgroundImage))
                self.backgroundImageLabel.setObjectName("backgroundImageLabel")
                self.instructionsLabel = QtWidgets.QLabel(self.centralwidget)
                self.instructionsLabel.setGeometry(QtCore.QRect(20, 140, 381, 81))
                palette = QtGui.QPalette()
                brush = QtGui.QBrush(QtGui.QColor(238, 238, 238))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
                brush = QtGui.QBrush(QtGui.QColor(238, 238, 238))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
                brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
                self.instructionsLabel.setPalette(palette)
                font = QtGui.QFont()
                font.setPointSize(15)
                font.setBold(False)
                font.setWeight(50)
                self.instructionsLabel.setFont(font)
                self.instructionsLabel.setObjectName("instructionsLabel")
                self.stateComboBox = QtWidgets.QComboBox(self.centralwidget)
                self.stateComboBox.setGeometry(QtCore.QRect(20, 270, 361, 31))
                palette = QtGui.QPalette()
                brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
                brush = QtGui.QBrush(QtGui.QColor(7, 55, 127))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
                brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
                brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
                brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
                brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
                brush = QtGui.QBrush(QtGui.QColor(7, 55, 127))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
                brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
                brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
                brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
                brush = QtGui.QBrush(QtGui.QColor(7, 55, 127))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
                brush = QtGui.QBrush(QtGui.QColor(7, 55, 127))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
                brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
                brush = QtGui.QBrush(QtGui.QColor(7, 55, 127))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
                brush = QtGui.QBrush(QtGui.QColor(7, 55, 127))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
                self.stateComboBox.setPalette(palette)
                font = QtGui.QFont()
                font.setPointSize(14)
                self.stateComboBox.setFont(font)
                self.stateComboBox.setStyleSheet("")
                self.stateComboBox.setObjectName("stateComboBox")
                for _ in range(len(stateList)): #for all 50 states (length of stateList)
                        self.stateComboBox.addItem("")
                self.searchButton = QtWidgets.QPushButton(self.centralwidget)
                self.searchButton.setGeometry(QtCore.QRect(20, 310, 181, 61))
                palette = QtGui.QPalette()
                brush = QtGui.QBrush(QtGui.QColor(131, 167, 189))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
                brush = QtGui.QBrush(QtGui.QColor(131, 167, 189))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
                brush = QtGui.QBrush(QtGui.QColor(131, 167, 189))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
                brush = QtGui.QBrush(QtGui.QColor(131, 167, 189))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
                brush = QtGui.QBrush(QtGui.QColor(131, 167, 189))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
                brush = QtGui.QBrush(QtGui.QColor(131, 167, 189))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
                brush = QtGui.QBrush(QtGui.QColor(131, 167, 189))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
                brush = QtGui.QBrush(QtGui.QColor(131, 167, 189))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
                brush = QtGui.QBrush(QtGui.QColor(131, 167, 189))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
                self.searchButton.setPalette(palette)
                font = QtGui.QFont()
                font.setFamily("qtquickcontrols")
                font.setPointSize(15)
                font.setBold(True)
                font.setWeight(75)
                self.searchButton.setFont(font)
                self.searchButton.setStyleSheet("background-color: rgb(131,167,189);\n"
        "border-radius: 10px;\n"
        "border :3px solid white")
                self.searchButton.setObjectName("searchButton")
                self.infoLabel = QtWidgets.QLabel(self.centralwidget)
                self.infoLabel.setGeometry(QtCore.QRect(30, 390, 381, 131))
                palette = QtGui.QPalette()
                brush = QtGui.QBrush(QtGui.QColor(245, 245, 245))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
                brush = QtGui.QBrush(QtGui.QColor(245, 245, 245))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
                brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
                self.infoLabel.setPalette(palette)
                font = QtGui.QFont()
                font.setPointSize(15)
                font.setBold(False)
                font.setWeight(50)
                self.infoLabel.setFont(font)
                self.infoLabel.setObjectName("infoLabel")
                self.forecastWidget = QtWidgets.QWidget(self.centralwidget)
                self.forecastWidget.setGeometry(QtCore.QRect(460, 20, 421, 511))
                self.forecastWidget.setObjectName("forecastWidget")
                self.forecastWidget.hide()
                self.day3_border = QtWidgets.QLabel(self.forecastWidget)
                self.day3_border.setGeometry(QtCore.QRect(10, 200, 401, 91))
                self.day3_border.setStyleSheet("\n"
        "border: 3px solid white;\n"
        "border-radius: 15px;")
                self.day3_border.setText("")
                self.day3_border.setObjectName("day3_border")
                self.highTempLabel_1 = QtWidgets.QLabel(self.forecastWidget)
                self.highTempLabel_1.setGeometry(QtCore.QRect(20, 30, 51, 31))
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.highTempLabel_1.sizePolicy().hasHeightForWidth())
                self.highTempLabel_1.setSizePolicy(sizePolicy)
                font = QtGui.QFont()
                font.setPointSize(17)
                self.highTempLabel_1.setFont(font)
                self.highTempLabel_1.setAutoFillBackground(False)
                self.highTempLabel_1.setObjectName("highTempLabel_1")
                self.UVImageLabel_2 = QtWidgets.QLabel(self.forecastWidget)
                self.UVImageLabel_2.setGeometry(QtCore.QRect(270, 140, 41, 41))
                self.UVImageLabel_2.setText("")
                self.UVImageLabel_2.setPixmap(QtGui.QPixmap(sunImage))
                self.UVImageLabel_2.setScaledContents(True)
                self.UVImageLabel_2.setObjectName("UVImageLabel_2")
                self.percipImageLabel_2 = QtWidgets.QLabel(self.forecastWidget)
                self.percipImageLabel_2.setGeometry(QtCore.QRect(270, 110, 41, 31))
                self.percipImageLabel_2.setText("")
                self.percipImageLabel_2.setPixmap(QtGui.QPixmap(percipImage))
                self.percipImageLabel_2.setScaledContents(True)
                self.percipImageLabel_2.setObjectName("percipImageLabel_2")
                self.UVLabel = QtWidgets.QLabel(self.forecastWidget)
                self.UVLabel.setGeometry(QtCore.QRect(310, 50, 51, 21))
                palette = QtGui.QPalette()
                brush = QtGui.QBrush(QtGui.QColor(94, 94, 94))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
                brush = QtGui.QBrush(QtGui.QColor(94, 94, 94))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
                brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
                self.UVLabel.setPalette(palette)
                font = QtGui.QFont()
                font.setPointSize(13)
                font.setBold(False)
                font.setWeight(50)
                self.UVLabel.setFont(font)
                self.UVLabel.setObjectName("UVLabel")
                self.percipLevelLabel_1 = QtWidgets.QLabel(self.forecastWidget)
                self.percipLevelLabel_1.setGeometry(QtCore.QRect(310, 10, 51, 31))
                palette = QtGui.QPalette()
                brush = QtGui.QBrush(QtGui.QColor(94, 94, 94))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
                brush = QtGui.QBrush(QtGui.QColor(94, 94, 94))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
                brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
                self.percipLevelLabel_1.setPalette(palette)
                font = QtGui.QFont()
                font.setPointSize(13)
                font.setBold(False)
                font.setWeight(50)
                self.percipLevelLabel_1.setFont(font)
                self.percipLevelLabel_1.setObjectName("percipLevelLabel_1")
                self.UVLabel_2 = QtWidgets.QLabel(self.forecastWidget)
                self.UVLabel_2.setGeometry(QtCore.QRect(310, 150, 51, 21))
                palette = QtGui.QPalette()
                brush = QtGui.QBrush(QtGui.QColor(94, 94, 94))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
                brush = QtGui.QBrush(QtGui.QColor(94, 94, 94))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
                brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
                self.UVLabel_2.setPalette(palette)
                font = QtGui.QFont()
                font.setPointSize(13)
                font.setBold(False)
                font.setWeight(50)
                self.UVLabel_2.setFont(font)
                self.UVLabel_2.setObjectName("UVLabel_2")
                self.percipLevelLabel_4 = QtWidgets.QLabel(self.forecastWidget)
                self.percipLevelLabel_4.setGeometry(QtCore.QRect(310, 310, 51, 31))
                palette = QtGui.QPalette()
                brush = QtGui.QBrush(QtGui.QColor(94, 94, 94))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
                brush = QtGui.QBrush(QtGui.QColor(94, 94, 94))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
                brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
                self.percipLevelLabel_4.setPalette(palette)
                font = QtGui.QFont()
                font.setPointSize(13)
                font.setBold(False)
                font.setWeight(50)
                self.percipLevelLabel_4.setFont(font)
                self.percipLevelLabel_4.setObjectName("percipLevelLabel_4")
                self.day1_image_4 = QtWidgets.QLabel(self.forecastWidget)
                self.day1_image_4.setEnabled(True)
                self.day1_image_4.setGeometry(QtCore.QRect(90, 310, 71, 71))
                self.day1_image_4.setText("")
                self.day1_image_4.setPixmap(QtGui.QPixmap(":/newPrefix/10d@2x.png"))
                self.day1_image_4.setScaledContents(True)
                self.day1_image_4.setAlignment(QtCore.Qt.AlignCenter)
                self.day1_image_4.setObjectName("day1_image_4")
                self.day3_date = QtWidgets.QLabel(self.forecastWidget)
                self.day3_date.setGeometry(QtCore.QRect(190, 200, 51, 31))
                font = QtGui.QFont()
                font.setPointSize(10)
                font.setBold(True)
                font.setUnderline(True)
                font.setWeight(75)
                self.day3_date.setFont(font)
                self.day3_date.setObjectName("day3_date")
                self.day5_date = QtWidgets.QLabel(self.forecastWidget)
                self.day5_date.setGeometry(QtCore.QRect(190, 400, 51, 31))
                font = QtGui.QFont()
                font.setPointSize(10)
                font.setBold(True)
                font.setUnderline(True)
                font.setWeight(75)
                self.day5_date.setFont(font)
                self.day5_date.setObjectName("day5_date")
                self.day1_image_3 = QtWidgets.QLabel(self.forecastWidget)
                self.day1_image_3.setEnabled(True)
                self.day1_image_3.setGeometry(QtCore.QRect(90, 210, 71, 71))
                self.day1_image_3.setText("")
                self.day1_image_3.setPixmap(QtGui.QPixmap(":/newPrefix/10d@2x.png"))
                self.day1_image_3.setScaledContents(True)
                self.day1_image_3.setAlignment(QtCore.Qt.AlignCenter)
                self.day1_image_3.setObjectName("day1_image_3")
                self.day2_border = QtWidgets.QLabel(self.forecastWidget)
                self.day2_border.setGeometry(QtCore.QRect(10, 100, 401, 91))
                self.day2_border.setStyleSheet("\n"
        "border: 3px solid white;\n"
        "border-radius: 15px;")
                self.day2_border.setText("")
                self.day2_border.setObjectName("day2_border")
                self.percipLevelLabel_5 = QtWidgets.QLabel(self.forecastWidget)
                self.percipLevelLabel_5.setGeometry(QtCore.QRect(310, 410, 51, 31))
                palette = QtGui.QPalette()
                brush = QtGui.QBrush(QtGui.QColor(94, 94, 94))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
                brush = QtGui.QBrush(QtGui.QColor(94, 94, 94))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
                brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
                self.percipLevelLabel_5.setPalette(palette)
                font = QtGui.QFont()
                font.setPointSize(13)
                font.setBold(False)
                font.setWeight(50)
                self.percipLevelLabel_5.setFont(font)
                self.percipLevelLabel_5.setObjectName("percipLevelLabel_5")
                self.percipImageLabel_4 = QtWidgets.QLabel(self.forecastWidget)
                self.percipImageLabel_4.setGeometry(QtCore.QRect(270, 310, 41, 31))
                self.percipImageLabel_4.setText("")
                self.percipImageLabel_4.setPixmap(QtGui.QPixmap(percipImage))
                self.percipImageLabel_4.setScaledContents(True)
                self.percipImageLabel_4.setObjectName("percipImageLabel_4")
                self.UVImageLabel_5 = QtWidgets.QLabel(self.forecastWidget)
                self.UVImageLabel_5.setGeometry(QtCore.QRect(270, 440, 41, 41))
                self.UVImageLabel_5.setText("")
                self.UVImageLabel_5.setPixmap(QtGui.QPixmap(sunImage))
                self.UVImageLabel_5.setScaledContents(True)
                self.UVImageLabel_5.setObjectName("UVImageLabel_5")
                self.weatherMain_4 = QtWidgets.QLabel(self.forecastWidget)
                self.weatherMain_4.setGeometry(QtCore.QRect(160, 330, 111, 31))
                self.weatherMain_4 = QtWidgets.QLabel(self.forecastWidget)
                self.weatherMain_4.setGeometry(QtCore.QRect(160, 330, 111, 51))
                palette = QtGui.QPalette()
                brush = QtGui.QBrush(QtGui.QColor(94, 94, 94))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
                brush = QtGui.QBrush(QtGui.QColor(94, 94, 94))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
                brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
                self.weatherMain_4.setPalette(palette)
                font = QtGui.QFont()
                font.setPointSize(13)
                font.setBold(False)
                font.setWeight(50)
                self.weatherMain_4.setFont(font)
                self.weatherMain_4.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
                self.weatherMain_4.setObjectName("weatherMain_4")
                self.day2_date = QtWidgets.QLabel(self.forecastWidget)
                self.day2_date.setGeometry(QtCore.QRect(190, 100, 51, 31))
                font = QtGui.QFont()
                font.setPointSize(10)
                font.setBold(True)
                font.setUnderline(True)
                font.setWeight(75)
                self.day2_date.setFont(font)
                self.day2_date.setObjectName("day2_date")
                self.weatherMain_1 = QtWidgets.QLabel(self.forecastWidget)
                self.weatherMain_1.setGeometry(QtCore.QRect(160, 30, 111, 31))
                self.weatherMain_1 = QtWidgets.QLabel(self.forecastWidget)
                self.weatherMain_1.setGeometry(QtCore.QRect(160, 30, 121, 51))
                palette = QtGui.QPalette()
                brush = QtGui.QBrush(QtGui.QColor(94, 94, 94))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
                brush = QtGui.QBrush(QtGui.QColor(94, 94, 94))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
                brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
                self.weatherMain_1.setPalette(palette)
                font = QtGui.QFont()
                font.setPointSize(13)
                font.setBold(False)
                font.setWeight(50)
                self.weatherMain_1.setFont(font)
                self.weatherMain_1.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
                self.weatherMain_1.setObjectName("weatherMain_1")
                self.percipLevelLabel_2 = QtWidgets.QLabel(self.forecastWidget)
                self.percipLevelLabel_2.setGeometry(QtCore.QRect(310, 110, 51, 31))
                palette = QtGui.QPalette()
                brush = QtGui.QBrush(QtGui.QColor(94, 94, 94))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
                brush = QtGui.QBrush(QtGui.QColor(94, 94, 94))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
                brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
                self.percipLevelLabel_2.setPalette(palette)
                font = QtGui.QFont()
                font.setPointSize(13)
                font.setBold(False)
                font.setWeight(50)
                self.percipLevelLabel_2.setFont(font)
                self.percipLevelLabel_2.setObjectName("percipLevelLabel_2")
                self.day1_border = QtWidgets.QLabel(self.forecastWidget)
                self.day1_border.setGeometry(QtCore.QRect(10, 0, 401, 91))
                self.day1_border.setStyleSheet("\n"
        "border: 3px solid white;\n"
        "border-radius: 15px;")
                self.day1_border.setText("")
                self.day1_border.setObjectName("day1_border")
                self.day5_border = QtWidgets.QLabel(self.forecastWidget)
                self.day5_border.setGeometry(QtCore.QRect(10, 400, 401, 91))
                self.day5_border.setStyleSheet("\n"
        "border: 3px solid white;\n"
        "border-radius: 15px;")
                self.day5_border.setText("")
                self.day5_border.setObjectName("day5_border")
                self.UVLabel_5 = QtWidgets.QLabel(self.forecastWidget)
                self.UVLabel_5.setGeometry(QtCore.QRect(310, 450, 51, 21))
                palette = QtGui.QPalette()
                brush = QtGui.QBrush(QtGui.QColor(94, 94, 94))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
                brush = QtGui.QBrush(QtGui.QColor(94, 94, 94))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
                brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
                self.UVLabel_5.setPalette(palette)
                font = QtGui.QFont()
                font.setPointSize(13)
                font.setBold(False)
                font.setWeight(50)
                self.UVLabel_5.setFont(font)
                self.UVLabel_5.setObjectName("UVLabel_5")
                self.percipImageLabel_5 = QtWidgets.QLabel(self.forecastWidget)
                self.percipImageLabel_5.setGeometry(QtCore.QRect(270, 410, 41, 31))
                self.percipImageLabel_5.setText("")
                self.percipImageLabel_5.setPixmap(QtGui.QPixmap(percipImage))
                self.percipImageLabel_5.setScaledContents(True)
                self.percipImageLabel_5.setObjectName("percipImageLabel_5")
                self.weatherMain_2 = QtWidgets.QLabel(self.forecastWidget)
                self.weatherMain_2.setGeometry(QtCore.QRect(160, 130, 111, 31))
                self.weatherMain_2 = QtWidgets.QLabel(self.forecastWidget)
                self.weatherMain_2.setGeometry(QtCore.QRect(160, 130, 121, 51))
                palette = QtGui.QPalette()
                brush = QtGui.QBrush(QtGui.QColor(94, 94, 94))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
                brush = QtGui.QBrush(QtGui.QColor(94, 94, 94))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
                brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
                self.weatherMain_2.setPalette(palette)
                font = QtGui.QFont()
                font.setPointSize(13)
                font.setBold(False)
                font.setWeight(50)
                self.weatherMain_2.setFont(font)
                self.weatherMain_2.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
                self.weatherMain_2.setObjectName("weatherMain_2")
                self.weatherMain_5 = QtWidgets.QLabel(self.forecastWidget)
                self.weatherMain_5.setGeometry(QtCore.QRect(160, 430, 111, 31))
                self.weatherMain_5 = QtWidgets.QLabel(self.forecastWidget)
                self.weatherMain_5.setGeometry(QtCore.QRect(150, 430, 121, 51))
                palette = QtGui.QPalette()
                brush = QtGui.QBrush(QtGui.QColor(94, 94, 94))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
                brush = QtGui.QBrush(QtGui.QColor(94, 94, 94))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
                brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
                self.weatherMain_5.setPalette(palette)
                font = QtGui.QFont()
                font.setPointSize(13)
                font.setBold(False)
                font.setWeight(50)
                self.weatherMain_5.setFont(font)
                self.weatherMain_5.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
                self.weatherMain_5.setObjectName("weatherMain_5")
                self.day1_image_2 = QtWidgets.QLabel(self.forecastWidget)
                self.day1_image_2.setEnabled(True)
                self.day1_image_2.setGeometry(QtCore.QRect(90, 110, 71, 71))
                self.day1_image_2.setText("")
                self.day1_image_2.setPixmap(QtGui.QPixmap(":/newPrefix/10d@2x.png"))
                self.day1_image_2.setScaledContents(True)
                self.day1_image_2.setAlignment(QtCore.Qt.AlignCenter)
                self.day1_image_2.setObjectName("day1_image_2")
                self.highTempLabel_5 = QtWidgets.QLabel(self.forecastWidget)
                self.highTempLabel_5.setGeometry(QtCore.QRect(20, 430, 51, 31))
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.highTempLabel_5.sizePolicy().hasHeightForWidth())
                self.highTempLabel_5.setSizePolicy(sizePolicy)
                font = QtGui.QFont()
                font.setPointSize(17)
                self.highTempLabel_5.setFont(font)
                self.highTempLabel_5.setObjectName("highTempLabel_5")
                self.highTempLabel_3 = QtWidgets.QLabel(self.forecastWidget)
                self.highTempLabel_3.setGeometry(QtCore.QRect(20, 230, 51, 31))
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.highTempLabel_3.sizePolicy().hasHeightForWidth())
                self.highTempLabel_3.setSizePolicy(sizePolicy)
                font = QtGui.QFont()
                font.setPointSize(17)
                self.highTempLabel_3.setFont(font)
                self.highTempLabel_3.setObjectName("highTempLabel_3")
                self.lowTempLabel_2 = QtWidgets.QLabel(self.forecastWidget)
                self.lowTempLabel_2.setGeometry(QtCore.QRect(60, 130, 51, 31))
                palette = QtGui.QPalette()
                brush = QtGui.QBrush(QtGui.QColor(94, 94, 94))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
                brush = QtGui.QBrush(QtGui.QColor(94, 94, 94))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
                brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
                self.lowTempLabel_2.setPalette(palette)
                font = QtGui.QFont()
                font.setPointSize(13)
                font.setBold(False)
                font.setWeight(50)
                self.lowTempLabel_2.setFont(font)
                self.lowTempLabel_2.setObjectName("lowTempLabel_2")
                self.UVLabel_3 = QtWidgets.QLabel(self.forecastWidget)
                self.UVLabel_3.setGeometry(QtCore.QRect(310, 250, 51, 21))
                palette = QtGui.QPalette()
                brush = QtGui.QBrush(QtGui.QColor(94, 94, 94))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
                brush = QtGui.QBrush(QtGui.QColor(94, 94, 94))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
                brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
                self.UVLabel_3.setPalette(palette)
                font = QtGui.QFont()
                font.setPointSize(13)
                font.setBold(False)
                font.setWeight(50)
                self.UVLabel_3.setFont(font)
                self.UVLabel_3.setObjectName("UVLabel_3")
                self.UVImageLabel_1 = QtWidgets.QLabel(self.forecastWidget)
                self.UVImageLabel_1.setGeometry(QtCore.QRect(270, 40, 41, 41))
                self.UVImageLabel_1.setText("")
                self.UVImageLabel_1.setPixmap(QtGui.QPixmap(sunImage))
                self.UVImageLabel_1.setScaledContents(True)
                self.UVImageLabel_1.setObjectName("UVImageLabel_1")
                self.weatherMain_3 = QtWidgets.QLabel(self.forecastWidget)
                self.weatherMain_3.setGeometry(QtCore.QRect(160, 230, 111, 31))
                self.weatherMain_3 = QtWidgets.QLabel(self.forecastWidget)
                self.weatherMain_3.setGeometry(QtCore.QRect(150, 230, 121, 51))
                palette = QtGui.QPalette()
                brush = QtGui.QBrush(QtGui.QColor(94, 94, 94))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
                brush = QtGui.QBrush(QtGui.QColor(94, 94, 94))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
                brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
                self.weatherMain_3.setPalette(palette)
                font = QtGui.QFont()
                font.setPointSize(13)
                font.setBold(False)
                font.setWeight(50)
                self.weatherMain_3.setFont(font)
                self.weatherMain_3.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
                self.weatherMain_3.setObjectName("weatherMain_3")
                self.UVImageLabel_3 = QtWidgets.QLabel(self.forecastWidget)
                self.UVImageLabel_3.setGeometry(QtCore.QRect(270, 240, 41, 41))
                self.UVImageLabel_3.setText("")
                self.UVImageLabel_3.setPixmap(QtGui.QPixmap(sunImage))
                self.UVImageLabel_3.setScaledContents(True)
                self.UVImageLabel_3.setObjectName("UVImageLabel_3")
                self.percipLevelLabel_3 = QtWidgets.QLabel(self.forecastWidget)
                self.percipLevelLabel_3.setGeometry(QtCore.QRect(310, 210, 51, 31))
                palette = QtGui.QPalette()
                brush = QtGui.QBrush(QtGui.QColor(94, 94, 94))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
                brush = QtGui.QBrush(QtGui.QColor(94, 94, 94))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
                brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
                self.percipLevelLabel_3.setPalette(palette)
                font = QtGui.QFont()
                font.setPointSize(13)
                font.setBold(False)
                font.setWeight(50)
                self.percipLevelLabel_3.setFont(font)
                self.percipLevelLabel_3.setObjectName("percipLevelLabel_3")
                self.day4_border = QtWidgets.QLabel(self.forecastWidget)
                self.day4_border.setGeometry(QtCore.QRect(10, 300, 401, 91))
                self.day4_border.setStyleSheet("\n"
        "border: 3px solid white;\n"
        "border-radius: 15px;")
                self.day4_border.setText("")
                self.day4_border.setObjectName("day4_border")
                self.highTempLabel_4 = QtWidgets.QLabel(self.forecastWidget)
                self.highTempLabel_4.setGeometry(QtCore.QRect(20, 330, 51, 31))
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.highTempLabel_4.sizePolicy().hasHeightForWidth())
                self.highTempLabel_4.setSizePolicy(sizePolicy)
                font = QtGui.QFont()
                font.setPointSize(17)
                self.highTempLabel_4.setFont(font)
                self.highTempLabel_4.setObjectName("highTempLabel_4")
                self.UVLabel_4 = QtWidgets.QLabel(self.forecastWidget)
                self.UVLabel_4.setGeometry(QtCore.QRect(310, 350, 51, 21))
                palette = QtGui.QPalette()
                brush = QtGui.QBrush(QtGui.QColor(94, 94, 94))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
                brush = QtGui.QBrush(QtGui.QColor(94, 94, 94))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
                brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
                self.UVLabel_4.setPalette(palette)
                font = QtGui.QFont()
                font.setPointSize(13)
                font.setBold(False)
                font.setWeight(50)
                self.UVLabel_4.setFont(font)
                self.UVLabel_4.setObjectName("UVLabel_4")
                self.day1_image_1 = QtWidgets.QLabel(self.forecastWidget)
                self.day1_image_1.setEnabled(True)
                self.day1_image_1.setGeometry(QtCore.QRect(90, 10, 71, 71))
                self.day1_image_1.setText("")
                self.day1_image_1.setPixmap(QtGui.QPixmap(":/newPrefix/10d@2x.png"))
                self.day1_image_1.setScaledContents(True)
                self.day1_image_1.setAlignment(QtCore.Qt.AlignCenter)
                self.day1_image_1.setObjectName("day1_image_1")
                self.day1_image_5 = QtWidgets.QLabel(self.forecastWidget)
                self.day1_image_5.setEnabled(True)
                self.day1_image_5.setGeometry(QtCore.QRect(90, 410, 71, 71))
                self.day1_image_5.setText("")
                self.day1_image_5.setPixmap(QtGui.QPixmap(":/newPrefix/10d@2x.png"))
                self.day1_image_5.setScaledContents(True)
                self.day1_image_5.setAlignment(QtCore.Qt.AlignCenter)
                self.day1_image_5.setObjectName("day1_image_5")
                self.lowTempLabel_4 = QtWidgets.QLabel(self.forecastWidget)
                self.lowTempLabel_4.setGeometry(QtCore.QRect(60, 330, 51, 31))
                palette = QtGui.QPalette()
                brush = QtGui.QBrush(QtGui.QColor(94, 94, 94))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
                brush = QtGui.QBrush(QtGui.QColor(94, 94, 94))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
                brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
                self.lowTempLabel_4.setPalette(palette)
                font = QtGui.QFont()
                font.setPointSize(13)
                font.setBold(False)
                font.setWeight(50)
                self.lowTempLabel_4.setFont(font)
                self.lowTempLabel_4.setObjectName("lowTempLabel_4")
                self.lowTempLabel_5 = QtWidgets.QLabel(self.forecastWidget)
                self.lowTempLabel_5.setGeometry(QtCore.QRect(60, 430, 51, 31))
                palette = QtGui.QPalette()
                brush = QtGui.QBrush(QtGui.QColor(94, 94, 94))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
                brush = QtGui.QBrush(QtGui.QColor(94, 94, 94))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
                brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
                self.lowTempLabel_5.setPalette(palette)
                font = QtGui.QFont()
                font.setPointSize(13)
                font.setBold(False)
                font.setWeight(50)
                self.lowTempLabel_5.setFont(font)
                self.lowTempLabel_5.setObjectName("lowTempLabel_5")
                self.percipImageLabel_1 = QtWidgets.QLabel(self.forecastWidget)
                self.percipImageLabel_1.setGeometry(QtCore.QRect(270, 10, 41, 31))
                self.percipImageLabel_1.setText("")
                self.percipImageLabel_1.setPixmap(QtGui.QPixmap(percipImage))
                self.percipImageLabel_1.setScaledContents(True)
                self.percipImageLabel_1.setObjectName("percipImageLabel_1")
                self.percipImageLabel_3 = QtWidgets.QLabel(self.forecastWidget)
                self.percipImageLabel_3.setGeometry(QtCore.QRect(270, 210, 41, 31))
                self.percipImageLabel_3.setText("")
                self.percipImageLabel_3.setPixmap(QtGui.QPixmap(percipImage))
                self.percipImageLabel_3.setScaledContents(True)
                self.percipImageLabel_3.setObjectName("percipImageLabel_3")
                self.day4_date = QtWidgets.QLabel(self.forecastWidget)
                self.day4_date.setGeometry(QtCore.QRect(190, 300, 51, 31))
                font = QtGui.QFont()
                font.setPointSize(10)
                font.setBold(True)
                font.setUnderline(True)
                font.setWeight(75)
                self.day4_date.setFont(font)
                self.day4_date.setObjectName("day4_date")
                self.lowTempLabel_3 = QtWidgets.QLabel(self.forecastWidget)
                self.lowTempLabel_3.setGeometry(QtCore.QRect(60, 230, 51, 31))
                palette = QtGui.QPalette()
                brush = QtGui.QBrush(QtGui.QColor(94, 94, 94))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
                brush = QtGui.QBrush(QtGui.QColor(94, 94, 94))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
                brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
                self.lowTempLabel_3.setPalette(palette)
                font = QtGui.QFont()
                font.setPointSize(13)
                font.setBold(False)
                font.setWeight(50)
                self.lowTempLabel_3.setFont(font)
                self.lowTempLabel_3.setObjectName("lowTempLabel_3")
                self.day1_date = QtWidgets.QLabel(self.forecastWidget)
                self.day1_date.setGeometry(QtCore.QRect(190, 0, 51, 31))
                font = QtGui.QFont()
                font.setPointSize(10)
                font.setBold(True)
                font.setUnderline(True)
                font.setWeight(75)
                self.day1_date.setFont(font)
                self.day1_date.setObjectName("day1_date")
                self.UVImageLabel_4 = QtWidgets.QLabel(self.forecastWidget)
                self.UVImageLabel_4.setGeometry(QtCore.QRect(270, 340, 41, 41))
                self.UVImageLabel_4.setText("")
                self.UVImageLabel_4.setPixmap(QtGui.QPixmap(sunImage))
                self.UVImageLabel_4.setScaledContents(True)
                self.UVImageLabel_4.setObjectName("UVImageLabel_4")
                self.highTempLabel_2 = QtWidgets.QLabel(self.forecastWidget)
                self.highTempLabel_2.setGeometry(QtCore.QRect(20, 130, 51, 31))
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.highTempLabel_2.sizePolicy().hasHeightForWidth())
                self.highTempLabel_2.setSizePolicy(sizePolicy)
                font = QtGui.QFont()
                font.setPointSize(17)
                self.highTempLabel_2.setFont(font)
                self.highTempLabel_2.setObjectName("highTempLabel_2")
                self.lowTempLabel_1 = QtWidgets.QLabel(self.forecastWidget)
                self.lowTempLabel_1.setGeometry(QtCore.QRect(60, 30, 51, 31))
                palette = QtGui.QPalette()
                brush = QtGui.QBrush(QtGui.QColor(94, 94, 94))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
                brush = QtGui.QBrush(QtGui.QColor(94, 94, 94))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
                brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
                self.lowTempLabel_1.setPalette(palette)
                font = QtGui.QFont()
                font.setPointSize(13)
                font.setBold(False)
                font.setWeight(50)
                self.lowTempLabel_1.setFont(font)
                self.lowTempLabel_1.setObjectName("lowTempLabel_1")
                self.cityTE = QtWidgets.QTextEdit(self.centralwidget)
                self.cityTE.setGeometry(QtCore.QRect(20, 230, 361, 31))
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.cityTE.sizePolicy().hasHeightForWidth())
                self.cityTE.setSizePolicy(sizePolicy)
                font = QtGui.QFont()
                font.setPointSize(14)
                self.cityTE.setFont(font)
                self.cityTE.setFrameShape(QtWidgets.QFrame.NoFrame)
                self.cityTE.setFrameShadow(QtWidgets.QFrame.Plain)
                self.cityTE.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
                self.cityTE.setObjectName("cityTE")
                self.reset_button = QtWidgets.QPushButton(self.centralwidget)
                self.reset_button.setGeometry(QtCore.QRect(210, 310, 171, 61))
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.reset_button.sizePolicy().hasHeightForWidth())
                self.reset_button.setSizePolicy(sizePolicy)
                self.reset_button.setPalette(palette)
                font = QtGui.QFont()
                font.setFamily("qtquickcontrols")
                font.setPointSize(15)
                font.setBold(True)
                font.setWeight(75)
                self.reset_button.setFont(font)
                self.reset_button.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
                self.reset_button.setStyleSheet("background-color: rgb(131,167,189);\n"
        "border-radius: 10px;\n"
        "border :3px solid white")
                self.reset_button.setObjectName("reset_button")
                self.reset_button.hide()
                
                self.image1 = QtGui.QImage()
                self.image2 = QtGui.QImage()
                self.image3 = QtGui.QImage()
                self.image4 = QtGui.QImage()
                self.image5 = QtGui.QImage()
                
                self.backgroundImageLabel.raise_()
                self.TitleLabel.raise_()
                self.cityTE.raise_()
                self.reset_button.raise_()
                self.instructionsLabel.raise_()
                self.stateComboBox.raise_()
                self.searchButton.raise_()
                self.infoLabel.raise_()
                self.forecastWidget.raise_()
                MainWindow.setCentralWidget(self.centralwidget)

                self.retranslateUi(MainWindow)

                QtCore.QMetaObject.connectSlotsByName(MainWindow)

        
        def retranslateUi(self, MainWindow):
                
                _translate = QtCore.QCoreApplication.translate
                MainWindow.setWindowTitle(_translate("MainWindow", "Forecasting App - Will G"))
                self.TitleLabel.setText(_translate("MainWindow", "5 DAY\nForecast"))
                self.instructionsLabel.setText(_translate("MainWindow", "Enter your city and state below to get your\nweather forecast!"))
                self.stateComboBox.setItemText(0, _translate("MainWindow", "State"))
                for stateNum in range(len(stateList)): #for each state - add to combo box
                        self.stateComboBox.setItemText(stateNum, _translate("MainWindow", stateList[stateNum]))
                self.searchButton.setText(_translate("MainWindow", "Search"))
                self.infoLabel.setText(_translate("MainWindow", "Enter your city and state"))
                self.cityTE.setPlaceholderText(_translate("MainWindow", "City"))
                self.reset_button.setText(_translate("MainWindow", "Reset"))

                self.searchButton.clicked.connect(self.get_lat_lon) #when search button is clicked, run get_lat_lon (line 1312)
                self.reset_button.clicked.connect(self.reset_screen) #when reset button is clicked, run reset_screen (line 1455)        
        #-------------------------------------(End) Code to generate UI------------------------------------------

        #--------------------------------------(Start) Functions-------------------------------------------------
        def get_lat_lon(self): #convert city, state -> latittude, longitude for API
                
                self.forecastWidget.hide()
                
                self.city = str(self.cityTE.toPlainText()).strip() #get city from text box
                self.state = str(self.stateComboBox.currentText()) #get state from combo box
                self.location_r = requests.get(f'http://api.openweathermap.org/geo/1.0/direct?q={self.city},{self.state},US&limit=1&appid={API_KEY}') #request to get location info (city,state,latittude,longitude)
                if(self.location_r.ok): #if the request is a [200]
                        self.location_info = json.loads(self.location_r.text) #jsonify the location request for parsing

                        if(self.location_info == []): #if the api returns blank (bad info)
                                
                                self.infoLabel.setText("Invalid city or state") #show the user they mistyped
                                QtWidgets.QApplication.processEvents() #update UI
                                return #allow the user to enter info again

                        self.infoLabel.setText("Getting weather forecast...") #show user it is getting the forecast

                        QtWidgets.QApplication.processEvents()
                        print(self.location_info) #test print

                        QtWidgets.QApplication.processEvents() #update UI

                        self.lat = (self.location_info[0]['lat']) #get lattitiude
                        self.lon = (self.location_info[0]['lon']) #get longitutude
                        self.city = (self.location_info[0]['name']) #official city
                        self.state = (self.location_info[0]['state']) #coutry

                        self.get_forcast() #send lat and lon to get weather 

        def get_forcast(self): #send request to weather API to get forecast

                self.weather_r = requests.get(f'https://api.openweathermap.org/data/2.5/onecall?lat={self.lat}&lon={self.lon}&exclude=current,hourly,minutely&appid={API_KEY}&units=imperial')
                self.weather_info = json.loads(self.weather_r.text) #jsonify the api info
                self.forecast_raw = [] #empty list to store daily forecast
                for day_number in range(6): # Add all 5 days to a list to be sent out for formatting
                        self.forcast_raw = [] #empty list to store daily forecast
                        for day_number in range(6): # Add all 5 days to a list to be sent out for formatting
                                if(day_number == 0): #skip the fist day of forecast (today)
                                        continue
                                self.forecast_raw.append(self.weather_info['daily'][day_number])
                        self.seperate_days(self.forecast_raw) #run spereate days function
                
        def seperate_days(self, dayList): #store the data in lists for corresponding day number
                
                self.dates = []
                self.high_temps = []
                self.low_temps = []
                self.main_weather = []
                self.images = []
                self.percips = []
                self.uvis = []

                for day in dayList: #go through each day in the list
                        day_info = day
                        
                        unix_dt = day_info['dt'] #dateTime in unix, to be converted
                        high_temp = round(float(day_info['temp']['max'])) #highest temp
                        low_temp = round(float(day_info['temp']['min'])) #lowest temp

                        main_weather = day_info['weather'][0]['description'] #main weather forecast description

                        main_weather = (day_info['weather'][0]['description']).title() #main weather forecast description

                        image = (f"https://openweathermap.org/img/wn/{day_info['weather'][0]['icon']}@2x.png")
                        precip = round(float(day_info['pop'])*100) #probability of precipitation 0 - 100
                        uvi = round(float(day_info['uvi'])) #UV index out of 10
                        
                        if(len(main_weather) > 14):
                                main_weather_split = main_weather.split(' ')
                                if (len(main_weather_split) == 2):
                                        main_weather = (f"{main_weather_split[0]}\n{main_weather_split[1]}").title()
                                elif (len(main_weather_split) == 3):
                                        main_weather = (f"{main_weather_split[0]}\n{main_weather_split[1]}\n{main_weather_split[2]}").title()
                                else:
                                        main_weather = (f"{main_weather_split[0]} {main_weather_split[1]}\n{main_weather_split[2]} {main_weather_split[3]}").title()
                        
                        formatted_time = datetime.fromtimestamp(unix_dt).strftime('%a %d') #formats time like 'Mon 18'
                        
                        self.dates.append(formatted_time)
                        self.high_temps.append(high_temp)
                        self.low_temps.append(low_temp)
                        self.main_weather.append(main_weather)
                        self.images.append(image)
                        self.percips.append(precip)
                        self.uvis.append(uvi)
                        
                self.output_weather()
                
        def output_weather(self): #push data from weather api to UI 
                
                self.day1_date.setText(f"{self.dates[0]}")
                self.day2_date.setText(f"{self.dates[1]}")
                self.day3_date.setText(f"{self.dates[2]}")
                self.day4_date.setText(f"{self.dates[3]}")
                self.day5_date.setText(f"{self.dates[4]}")
                
                self.highTempLabel_1.setText(f"{self.high_temps[0]}°")
                self.highTempLabel_2.setText(f"{self.high_temps[1]}°")
                self.highTempLabel_3.setText(f"{self.high_temps[2]}°")
                self.highTempLabel_4.setText(f"{self.high_temps[3]}°")
                self.highTempLabel_5.setText(f"{self.high_temps[4]}°")
                
                self.lowTempLabel_1.setText(f"/{self.low_temps[0]}°")
                self.lowTempLabel_2.setText(f"/{self.low_temps[1]}°")
                self.lowTempLabel_3.setText(f"/{self.low_temps[2]}°")
                self.lowTempLabel_4.setText(f"/{self.low_temps[3]}°")
                self.lowTempLabel_5.setText(f"/{self.low_temps[4]}°")
                
                self.weatherMain_1.setText(f"{self.main_weather[0]}")
                self.weatherMain_2.setText(f"{self.main_weather[1]}")
                self.weatherMain_3.setText(f"{self.main_weather[2]}")
                self.weatherMain_4.setText(f"{self.main_weather[3]}")
                self.weatherMain_5.setText(f"{self.main_weather[4]}")
                
                self.image1.loadFromData(requests.get(self.images[0]).content)
                self.image2.loadFromData(requests.get(self.images[1]).content)
                self.image3.loadFromData(requests.get(self.images[2]).content)
                self.image4.loadFromData(requests.get(self.images[3]).content)
                self.image5.loadFromData(requests.get(self.images[4]).content)
                
                self.day1_image_1.setPixmap(QtGui.QPixmap(self.image1))
                self.day1_image_2.setPixmap(QtGui.QPixmap(self.image2))
                self.day1_image_3.setPixmap(QtGui.QPixmap(self.image3))
                self.day1_image_4.setPixmap(QtGui.QPixmap(self.image4))
                self.day1_image_5.setPixmap(QtGui.QPixmap(self.image5))
                
                self.percipLevelLabel_1.setText(f"{self.percips[0]}%")
                self.percipLevelLabel_2.setText(f"{self.percips[1]}%")
                self.percipLevelLabel_3.setText(f"{self.percips[2]}%")
                self.percipLevelLabel_4.setText(f"{self.percips[3]}%")
                self.percipLevelLabel_5.setText(f"{self.percips[4]}%")
                
                self.UVLabel.setText(f"{self.uvis[0]}/10")
                self.UVLabel_2.setText(f"{self.uvis[1]}/10")
                self.UVLabel_3.setText(f"{self.uvis[2]}/10")
                self.UVLabel_4.setText(f"{self.uvis[3]}/10")
                self.UVLabel_5.setText(f"{self.uvis[4]}/10")
                
                self.forecastWidget.show()
                self.reset_button.show()

                self.infoLabel.setText(f"Here is your forecast!\n{self.city}, {self.state}\n\n{self.lat}, {self.lon}")
                
                QtWidgets.QApplication.processEvents()
                
        def reset_screen(self): #reset all widgets to how they were at the start
                self.forecastWidget.hide()
                self.infoLabel.setText("Enter your city and state")
                self.stateComboBox.setCurrentIndex(0)
                self.cityTE.setText("")
                self.cityTE.setPlaceholderText("City")
                self.reset_button.hide()
        #--------------------------------------(End) Functions-------------------------------------------------------
                


#----------------------------------------(Start) MAIN-----------------------------------
if __name__ == "__main__":
    
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
#----------------------------------------(End) MAIN--------------------------------------