# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'u2.ui'
##
## Created by: Qt User Interface Compiler version 6.1.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import *
from PySide6.QtGui import *
from PySide6.QtWidgets import *

import test_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(898, 564)
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QSize(898, 564))
        MainWindow.setMaximumSize(QSize(898, 564))
        palette = QPalette()
        brush = QBrush(QColor(0, 0, 0, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush1 = QBrush(QColor(255, 255, 255, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette.setBrush(QPalette.Active, QPalette.Light, brush1)
        palette.setBrush(QPalette.Active, QPalette.Midlight, brush1)
        brush2 = QBrush(QColor(127, 127, 127, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Dark, brush2)
        brush3 = QBrush(QColor(170, 170, 170, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Mid, brush3)
        palette.setBrush(QPalette.Active, QPalette.Text, brush)
        palette.setBrush(QPalette.Active, QPalette.BrightText, brush1)
        palette.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette.setBrush(QPalette.Active, QPalette.Shadow, brush)
        palette.setBrush(QPalette.Active, QPalette.AlternateBase, brush1)
        brush4 = QBrush(QColor(255, 255, 220, 255))
        brush4.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.ToolTipBase, brush4)
        palette.setBrush(QPalette.Active, QPalette.ToolTipText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Light, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Midlight, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Dark, brush2)
        palette.setBrush(QPalette.Inactive, QPalette.Mid, brush3)
        palette.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette.setBrush(QPalette.Inactive, QPalette.BrightText, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Shadow, brush)
        palette.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush4)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush)
        palette.setBrush(QPalette.Disabled, QPalette.WindowText, brush2)
        palette.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Light, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Midlight, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Dark, brush2)
        palette.setBrush(QPalette.Disabled, QPalette.Mid, brush3)
        palette.setBrush(QPalette.Disabled, QPalette.Text, brush2)
        palette.setBrush(QPalette.Disabled, QPalette.BrightText, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.ButtonText, brush2)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Shadow, brush)
        palette.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush)
        MainWindow.setPalette(palette)
        font = QFont()
        font.setFamilies([u"MS Shell Dlg 2"])
        font.setBold(True)
        MainWindow.setFont(font)
        MainWindow.setTabShape(QTabWidget.Triangular)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.TitleLabel = QLabel(self.centralwidget)
        self.TitleLabel.setObjectName(u"TitleLabel")
        self.TitleLabel.setGeometry(QRect(20, 0, 321, 161))
        sizePolicy.setHeightForWidth(self.TitleLabel.sizePolicy().hasHeightForWidth())
        self.TitleLabel.setSizePolicy(sizePolicy)
        palette1 = QPalette()
        palette1.setBrush(QPalette.Active, QPalette.WindowText, brush1)
        palette1.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette1.setBrush(QPalette.Active, QPalette.Light, brush1)
        palette1.setBrush(QPalette.Active, QPalette.Midlight, brush1)
        palette1.setBrush(QPalette.Active, QPalette.Dark, brush2)
        palette1.setBrush(QPalette.Active, QPalette.Mid, brush3)
        palette1.setBrush(QPalette.Active, QPalette.Text, brush)
        palette1.setBrush(QPalette.Active, QPalette.BrightText, brush1)
        palette1.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette1.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette1.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette1.setBrush(QPalette.Active, QPalette.Shadow, brush)
        palette1.setBrush(QPalette.Active, QPalette.AlternateBase, brush1)
        palette1.setBrush(QPalette.Active, QPalette.ToolTipBase, brush4)
        palette1.setBrush(QPalette.Active, QPalette.ToolTipText, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.WindowText, brush1)
        palette1.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette1.setBrush(QPalette.Inactive, QPalette.Light, brush1)
        palette1.setBrush(QPalette.Inactive, QPalette.Midlight, brush1)
        palette1.setBrush(QPalette.Inactive, QPalette.Dark, brush2)
        palette1.setBrush(QPalette.Inactive, QPalette.Mid, brush3)
        palette1.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.BrightText, brush1)
        palette1.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette1.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette1.setBrush(QPalette.Inactive, QPalette.Shadow, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush1)
        palette1.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush4)
        palette1.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush)
        palette1.setBrush(QPalette.Disabled, QPalette.WindowText, brush2)
        palette1.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette1.setBrush(QPalette.Disabled, QPalette.Light, brush1)
        palette1.setBrush(QPalette.Disabled, QPalette.Midlight, brush1)
        palette1.setBrush(QPalette.Disabled, QPalette.Dark, brush2)
        palette1.setBrush(QPalette.Disabled, QPalette.Mid, brush3)
        palette1.setBrush(QPalette.Disabled, QPalette.Text, brush2)
        palette1.setBrush(QPalette.Disabled, QPalette.BrightText, brush1)
        palette1.setBrush(QPalette.Disabled, QPalette.ButtonText, brush2)
        palette1.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette1.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        palette1.setBrush(QPalette.Disabled, QPalette.Shadow, brush)
        palette1.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush1)
        palette1.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush4)
        palette1.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush)
        self.TitleLabel.setPalette(palette1)
        font1 = QFont()
        font1.setFamilies([u"qtquickcontrols"])
        font1.setPointSize(45)
        font1.setBold(True)
        font1.setStrikeOut(False)
        font1.setKerning(True)
        self.TitleLabel.setFont(font1)
        self.backgroundImageLabel = QLabel(self.centralwidget)
        self.backgroundImageLabel.setObjectName(u"backgroundImageLabel")
        self.backgroundImageLabel.setGeometry(QRect(-10, -30, 921, 611))
        font2 = QFont()
        font2.setFamilies([u"MV Boli"])
        self.backgroundImageLabel.setFont(font2)
        self.backgroundImageLabel.setPixmap(QPixmap(u":/newPrefix/pictures/Untitled.png"))
        self.instructionsLabel = QLabel(self.centralwidget)
        self.instructionsLabel.setObjectName(u"instructionsLabel")
        self.instructionsLabel.setGeometry(QRect(20, 140, 381, 81))
        palette2 = QPalette()
        brush5 = QBrush(QColor(238, 238, 238, 255))
        brush5.setStyle(Qt.SolidPattern)
        palette2.setBrush(QPalette.Active, QPalette.WindowText, brush5)
        palette2.setBrush(QPalette.Inactive, QPalette.WindowText, brush5)
        palette2.setBrush(QPalette.Disabled, QPalette.WindowText, brush2)
        self.instructionsLabel.setPalette(palette2)
        font3 = QFont()
        font3.setPointSize(15)
        font3.setBold(False)
        self.instructionsLabel.setFont(font3)
        self.stateComboBox = QComboBox(self.centralwidget)
        self.stateComboBox.addItem("")
        self.stateComboBox.addItem("")
        self.stateComboBox.addItem("")
        self.stateComboBox.addItem("")
        self.stateComboBox.addItem("")
        self.stateComboBox.addItem("")
        self.stateComboBox.addItem("")
        self.stateComboBox.addItem("")
        self.stateComboBox.addItem("")
        self.stateComboBox.addItem("")
        self.stateComboBox.addItem("")
        self.stateComboBox.addItem("")
        self.stateComboBox.addItem("")
        self.stateComboBox.addItem("")
        self.stateComboBox.addItem("")
        self.stateComboBox.addItem("")
        self.stateComboBox.addItem("")
        self.stateComboBox.addItem("")
        self.stateComboBox.addItem("")
        self.stateComboBox.addItem("")
        self.stateComboBox.addItem("")
        self.stateComboBox.addItem("")
        self.stateComboBox.addItem("")
        self.stateComboBox.addItem("")
        self.stateComboBox.addItem("")
        self.stateComboBox.addItem("")
        self.stateComboBox.addItem("")
        self.stateComboBox.addItem("")
        self.stateComboBox.addItem("")
        self.stateComboBox.addItem("")
        self.stateComboBox.addItem("")
        self.stateComboBox.addItem("")
        self.stateComboBox.addItem("")
        self.stateComboBox.addItem("")
        self.stateComboBox.addItem("")
        self.stateComboBox.addItem("")
        self.stateComboBox.addItem("")
        self.stateComboBox.addItem("")
        self.stateComboBox.addItem("")
        self.stateComboBox.addItem("")
        self.stateComboBox.addItem("")
        self.stateComboBox.addItem("")
        self.stateComboBox.addItem("")
        self.stateComboBox.addItem("")
        self.stateComboBox.addItem("")
        self.stateComboBox.addItem("")
        self.stateComboBox.addItem("")
        self.stateComboBox.addItem("")
        self.stateComboBox.addItem("")
        self.stateComboBox.addItem("")
        self.stateComboBox.setObjectName(u"stateComboBox")
        self.stateComboBox.setGeometry(QRect(20, 270, 361, 31))
        palette3 = QPalette()
        palette3.setBrush(QPalette.Active, QPalette.WindowText, brush1)
        brush6 = QBrush(QColor(7, 55, 127, 255))
        brush6.setStyle(Qt.SolidPattern)
        palette3.setBrush(QPalette.Active, QPalette.Dark, brush6)
        brush7 = QBrush(QColor(255, 255, 0, 255))
        brush7.setStyle(Qt.SolidPattern)
        palette3.setBrush(QPalette.Active, QPalette.Mid, brush7)
        palette3.setBrush(QPalette.Active, QPalette.Text, brush)
        palette3.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette3.setBrush(QPalette.Inactive, QPalette.WindowText, brush1)
        palette3.setBrush(QPalette.Inactive, QPalette.Dark, brush6)
        palette3.setBrush(QPalette.Inactive, QPalette.Mid, brush7)
        palette3.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette3.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette3.setBrush(QPalette.Disabled, QPalette.WindowText, brush6)
        palette3.setBrush(QPalette.Disabled, QPalette.Dark, brush6)
        palette3.setBrush(QPalette.Disabled, QPalette.Mid, brush7)
        palette3.setBrush(QPalette.Disabled, QPalette.Text, brush6)
        palette3.setBrush(QPalette.Disabled, QPalette.ButtonText, brush6)
        self.stateComboBox.setPalette(palette3)
        font4 = QFont()
        font4.setPointSize(14)
        self.stateComboBox.setFont(font4)
        self.stateComboBox.setStyleSheet(u"")
        self.searchButton = QPushButton(self.centralwidget)
        self.searchButton.setObjectName(u"searchButton")
        self.searchButton.setGeometry(QRect(20, 320, 211, 61))
        palette4 = QPalette()
        brush8 = QBrush(QColor(131, 167, 189, 255))
        brush8.setStyle(Qt.SolidPattern)
        palette4.setBrush(QPalette.Active, QPalette.Button, brush8)
        palette4.setBrush(QPalette.Active, QPalette.Base, brush8)
        palette4.setBrush(QPalette.Active, QPalette.Window, brush8)
        palette4.setBrush(QPalette.Inactive, QPalette.Button, brush8)
        palette4.setBrush(QPalette.Inactive, QPalette.Base, brush8)
        palette4.setBrush(QPalette.Inactive, QPalette.Window, brush8)
        palette4.setBrush(QPalette.Disabled, QPalette.Button, brush8)
        palette4.setBrush(QPalette.Disabled, QPalette.Base, brush8)
        palette4.setBrush(QPalette.Disabled, QPalette.Window, brush8)
        self.searchButton.setPalette(palette4)
        font5 = QFont()
        font5.setFamilies([u"qtquickcontrols"])
        font5.setPointSize(15)
        font5.setBold(True)
        self.searchButton.setFont(font5)
        self.searchButton.setStyleSheet(u"background-color: rgb(131,167,189);\n"
"border-radius: 10px;")
        self.infoLabel = QLabel(self.centralwidget)
        self.infoLabel.setObjectName(u"infoLabel")
        self.infoLabel.setGeometry(QRect(30, 390, 381, 81))
        palette5 = QPalette()
        brush9 = QBrush(QColor(245, 245, 245, 255))
        brush9.setStyle(Qt.SolidPattern)
        palette5.setBrush(QPalette.Active, QPalette.WindowText, brush9)
        palette5.setBrush(QPalette.Inactive, QPalette.WindowText, brush9)
        palette5.setBrush(QPalette.Disabled, QPalette.WindowText, brush2)
        self.infoLabel.setPalette(palette5)
        self.infoLabel.setFont(font3)
        self.forcastWidget = QWidget(self.centralwidget)
        self.forcastWidget.setObjectName(u"forcastWidget")
        self.forcastWidget.setGeometry(QRect(460, 20, 421, 511))
        self.day3_border = QLabel(self.forcastWidget)
        self.day3_border.setObjectName(u"day3_border")
        self.day3_border.setGeometry(QRect(10, 200, 401, 91))
        self.day3_border.setStyleSheet(u"\n"
"border: 3px solid white;\n"
"border-radius: 15px;")
        self.highTempLabel = QLabel(self.forcastWidget)
        self.highTempLabel.setObjectName(u"highTempLabel")
        self.highTempLabel.setGeometry(QRect(20, 30, 51, 31))
        sizePolicy1 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Maximum)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.highTempLabel.sizePolicy().hasHeightForWidth())
        self.highTempLabel.setSizePolicy(sizePolicy1)
        font6 = QFont()
        font6.setPointSize(17)
        self.highTempLabel.setFont(font6)
        self.highTempLabel.setAutoFillBackground(False)
        self.UVImageLabel_2 = QLabel(self.forcastWidget)
        self.UVImageLabel_2.setObjectName(u"UVImageLabel_2")
        self.UVImageLabel_2.setGeometry(QRect(270, 140, 41, 41))
        self.UVImageLabel_2.setPixmap(QPixmap(u":/newPrefix/sun_469-removebg-preview.png"))
        self.UVImageLabel_2.setScaledContents(True)
        self.percipImageLabel_2 = QLabel(self.forcastWidget)
        self.percipImageLabel_2.setObjectName(u"percipImageLabel_2")
        self.percipImageLabel_2.setGeometry(QRect(270, 110, 41, 31))
        self.percipImageLabel_2.setPixmap(QPixmap(u":/newPrefix/5-57317_water-drop-clipart-png-transparent-png-removebg-preview.png"))
        self.percipImageLabel_2.setScaledContents(True)
        self.UVLabel = QLabel(self.forcastWidget)
        self.UVLabel.setObjectName(u"UVLabel")
        self.UVLabel.setGeometry(QRect(310, 50, 51, 21))
        palette6 = QPalette()
        brush10 = QBrush(QColor(94, 94, 94, 255))
        brush10.setStyle(Qt.SolidPattern)
        palette6.setBrush(QPalette.Active, QPalette.WindowText, brush10)
        palette6.setBrush(QPalette.Inactive, QPalette.WindowText, brush10)
        palette6.setBrush(QPalette.Disabled, QPalette.WindowText, brush2)
        self.UVLabel.setPalette(palette6)
        font7 = QFont()
        font7.setPointSize(13)
        font7.setBold(False)
        self.UVLabel.setFont(font7)
        self.percipLevelLabel = QLabel(self.forcastWidget)
        self.percipLevelLabel.setObjectName(u"percipLevelLabel")
        self.percipLevelLabel.setGeometry(QRect(310, 10, 51, 31))
        palette7 = QPalette()
        palette7.setBrush(QPalette.Active, QPalette.WindowText, brush10)
        palette7.setBrush(QPalette.Inactive, QPalette.WindowText, brush10)
        palette7.setBrush(QPalette.Disabled, QPalette.WindowText, brush2)
        self.percipLevelLabel.setPalette(palette7)
        self.percipLevelLabel.setFont(font7)
        self.UVLabel_2 = QLabel(self.forcastWidget)
        self.UVLabel_2.setObjectName(u"UVLabel_2")
        self.UVLabel_2.setGeometry(QRect(310, 150, 51, 21))
        palette8 = QPalette()
        palette8.setBrush(QPalette.Active, QPalette.WindowText, brush10)
        palette8.setBrush(QPalette.Inactive, QPalette.WindowText, brush10)
        palette8.setBrush(QPalette.Disabled, QPalette.WindowText, brush2)
        self.UVLabel_2.setPalette(palette8)
        self.UVLabel_2.setFont(font7)
        self.percipLevelLabel_4 = QLabel(self.forcastWidget)
        self.percipLevelLabel_4.setObjectName(u"percipLevelLabel_4")
        self.percipLevelLabel_4.setGeometry(QRect(310, 310, 51, 31))
        palette9 = QPalette()
        palette9.setBrush(QPalette.Active, QPalette.WindowText, brush10)
        palette9.setBrush(QPalette.Inactive, QPalette.WindowText, brush10)
        palette9.setBrush(QPalette.Disabled, QPalette.WindowText, brush2)
        self.percipLevelLabel_4.setPalette(palette9)
        self.percipLevelLabel_4.setFont(font7)
        self.day1_image_4 = QLabel(self.forcastWidget)
        self.day1_image_4.setObjectName(u"day1_image_4")
        self.day1_image_4.setEnabled(True)
        self.day1_image_4.setGeometry(QRect(100, 310, 71, 71))
        self.day1_image_4.setPixmap(QPixmap(u":/newPrefix/10d@2x.png"))
        self.day1_image_4.setScaledContents(True)
        self.day1_image_4.setAlignment(Qt.AlignCenter)
        self.day3_date = QLabel(self.forcastWidget)
        self.day3_date.setObjectName(u"day3_date")
        self.day3_date.setGeometry(QRect(190, 200, 51, 31))
        font8 = QFont()
        font8.setPointSize(10)
        font8.setBold(True)
        font8.setUnderline(True)
        self.day3_date.setFont(font8)
        self.day5_date = QLabel(self.forcastWidget)
        self.day5_date.setObjectName(u"day5_date")
        self.day5_date.setGeometry(QRect(190, 400, 51, 31))
        self.day5_date.setFont(font8)
        self.day1_image_3 = QLabel(self.forcastWidget)
        self.day1_image_3.setObjectName(u"day1_image_3")
        self.day1_image_3.setEnabled(True)
        self.day1_image_3.setGeometry(QRect(100, 210, 71, 71))
        self.day1_image_3.setPixmap(QPixmap(u":/newPrefix/10d@2x.png"))
        self.day1_image_3.setScaledContents(True)
        self.day1_image_3.setAlignment(Qt.AlignCenter)
        self.day2_border = QLabel(self.forcastWidget)
        self.day2_border.setObjectName(u"day2_border")
        self.day2_border.setGeometry(QRect(10, 100, 401, 91))
        self.day2_border.setStyleSheet(u"\n"
"border: 3px solid white;\n"
"border-radius: 15px;")
        self.percipLevelLabel_5 = QLabel(self.forcastWidget)
        self.percipLevelLabel_5.setObjectName(u"percipLevelLabel_5")
        self.percipLevelLabel_5.setGeometry(QRect(310, 410, 51, 31))
        palette10 = QPalette()
        palette10.setBrush(QPalette.Active, QPalette.WindowText, brush10)
        palette10.setBrush(QPalette.Inactive, QPalette.WindowText, brush10)
        palette10.setBrush(QPalette.Disabled, QPalette.WindowText, brush2)
        self.percipLevelLabel_5.setPalette(palette10)
        self.percipLevelLabel_5.setFont(font7)
        self.percipImageLabel_4 = QLabel(self.forcastWidget)
        self.percipImageLabel_4.setObjectName(u"percipImageLabel_4")
        self.percipImageLabel_4.setGeometry(QRect(270, 310, 41, 31))
        self.percipImageLabel_4.setPixmap(QPixmap(u":/newPrefix/5-57317_water-drop-clipart-png-transparent-png-removebg-preview.png"))
        self.percipImageLabel_4.setScaledContents(True)
        self.UVImageLabel_5 = QLabel(self.forcastWidget)
        self.UVImageLabel_5.setObjectName(u"UVImageLabel_5")
        self.UVImageLabel_5.setGeometry(QRect(270, 440, 41, 41))
        self.UVImageLabel_5.setPixmap(QPixmap(u":/newPrefix/sun_469-removebg-preview.png"))
        self.UVImageLabel_5.setScaledContents(True)
        self.weatherMain_4 = QLabel(self.forcastWidget)
        self.weatherMain_4.setObjectName(u"weatherMain_4")
        self.weatherMain_4.setGeometry(QRect(160, 330, 111, 31))
        palette11 = QPalette()
        palette11.setBrush(QPalette.Active, QPalette.WindowText, brush10)
        palette11.setBrush(QPalette.Inactive, QPalette.WindowText, brush10)
        palette11.setBrush(QPalette.Disabled, QPalette.WindowText, brush2)
        self.weatherMain_4.setPalette(palette11)
        self.weatherMain_4.setFont(font7)
        self.day2_date = QLabel(self.forcastWidget)
        self.day2_date.setObjectName(u"day2_date")
        self.day2_date.setGeometry(QRect(190, 100, 51, 31))
        self.day2_date.setFont(font8)
        self.weatherMain = QLabel(self.forcastWidget)
        self.weatherMain.setObjectName(u"weatherMain")
        self.weatherMain.setGeometry(QRect(160, 30, 111, 31))
        palette12 = QPalette()
        palette12.setBrush(QPalette.Active, QPalette.WindowText, brush10)
        palette12.setBrush(QPalette.Inactive, QPalette.WindowText, brush10)
        palette12.setBrush(QPalette.Disabled, QPalette.WindowText, brush2)
        self.weatherMain.setPalette(palette12)
        self.weatherMain.setFont(font7)
        self.percipLevelLabel_2 = QLabel(self.forcastWidget)
        self.percipLevelLabel_2.setObjectName(u"percipLevelLabel_2")
        self.percipLevelLabel_2.setGeometry(QRect(310, 110, 51, 31))
        palette13 = QPalette()
        palette13.setBrush(QPalette.Active, QPalette.WindowText, brush10)
        palette13.setBrush(QPalette.Inactive, QPalette.WindowText, brush10)
        palette13.setBrush(QPalette.Disabled, QPalette.WindowText, brush2)
        self.percipLevelLabel_2.setPalette(palette13)
        self.percipLevelLabel_2.setFont(font7)
        self.day1_border = QLabel(self.forcastWidget)
        self.day1_border.setObjectName(u"day1_border")
        self.day1_border.setGeometry(QRect(10, 0, 401, 91))
        self.day1_border.setStyleSheet(u"\n"
"border: 3px solid white;\n"
"border-radius: 15px;")
        self.day5_border = QLabel(self.forcastWidget)
        self.day5_border.setObjectName(u"day5_border")
        self.day5_border.setGeometry(QRect(10, 400, 401, 91))
        self.day5_border.setStyleSheet(u"\n"
"border: 3px solid white;\n"
"border-radius: 15px;")
        self.UVLabel_5 = QLabel(self.forcastWidget)
        self.UVLabel_5.setObjectName(u"UVLabel_5")
        self.UVLabel_5.setGeometry(QRect(310, 450, 51, 21))
        palette14 = QPalette()
        palette14.setBrush(QPalette.Active, QPalette.WindowText, brush10)
        palette14.setBrush(QPalette.Inactive, QPalette.WindowText, brush10)
        palette14.setBrush(QPalette.Disabled, QPalette.WindowText, brush2)
        self.UVLabel_5.setPalette(palette14)
        self.UVLabel_5.setFont(font7)
        self.percipImageLabel_5 = QLabel(self.forcastWidget)
        self.percipImageLabel_5.setObjectName(u"percipImageLabel_5")
        self.percipImageLabel_5.setGeometry(QRect(270, 410, 41, 31))
        self.percipImageLabel_5.setPixmap(QPixmap(u":/newPrefix/5-57317_water-drop-clipart-png-transparent-png-removebg-preview.png"))
        self.percipImageLabel_5.setScaledContents(True)
        self.weatherMain_2 = QLabel(self.forcastWidget)
        self.weatherMain_2.setObjectName(u"weatherMain_2")
        self.weatherMain_2.setGeometry(QRect(160, 130, 111, 31))
        palette15 = QPalette()
        palette15.setBrush(QPalette.Active, QPalette.WindowText, brush10)
        palette15.setBrush(QPalette.Inactive, QPalette.WindowText, brush10)
        palette15.setBrush(QPalette.Disabled, QPalette.WindowText, brush2)
        self.weatherMain_2.setPalette(palette15)
        self.weatherMain_2.setFont(font7)
        self.weatherMain_5 = QLabel(self.forcastWidget)
        self.weatherMain_5.setObjectName(u"weatherMain_5")
        self.weatherMain_5.setGeometry(QRect(160, 430, 111, 31))
        palette16 = QPalette()
        palette16.setBrush(QPalette.Active, QPalette.WindowText, brush10)
        palette16.setBrush(QPalette.Inactive, QPalette.WindowText, brush10)
        palette16.setBrush(QPalette.Disabled, QPalette.WindowText, brush2)
        self.weatherMain_5.setPalette(palette16)
        self.weatherMain_5.setFont(font7)
        self.day1_image_2 = QLabel(self.forcastWidget)
        self.day1_image_2.setObjectName(u"day1_image_2")
        self.day1_image_2.setEnabled(True)
        self.day1_image_2.setGeometry(QRect(100, 110, 71, 71))
        self.day1_image_2.setPixmap(QPixmap(u":/newPrefix/10d@2x.png"))
        self.day1_image_2.setScaledContents(True)
        self.day1_image_2.setAlignment(Qt.AlignCenter)
        self.highTempLabel_5 = QLabel(self.forcastWidget)
        self.highTempLabel_5.setObjectName(u"highTempLabel_5")
        self.highTempLabel_5.setGeometry(QRect(20, 430, 51, 31))
        sizePolicy1.setHeightForWidth(self.highTempLabel_5.sizePolicy().hasHeightForWidth())
        self.highTempLabel_5.setSizePolicy(sizePolicy1)
        self.highTempLabel_5.setFont(font6)
        self.highTempLabel_3 = QLabel(self.forcastWidget)
        self.highTempLabel_3.setObjectName(u"highTempLabel_3")
        self.highTempLabel_3.setGeometry(QRect(20, 230, 51, 31))
        sizePolicy1.setHeightForWidth(self.highTempLabel_3.sizePolicy().hasHeightForWidth())
        self.highTempLabel_3.setSizePolicy(sizePolicy1)
        self.highTempLabel_3.setFont(font6)
        self.lowTempLabel_2 = QLabel(self.forcastWidget)
        self.lowTempLabel_2.setObjectName(u"lowTempLabel_2")
        self.lowTempLabel_2.setGeometry(QRect(60, 130, 51, 31))
        palette17 = QPalette()
        palette17.setBrush(QPalette.Active, QPalette.WindowText, brush10)
        palette17.setBrush(QPalette.Inactive, QPalette.WindowText, brush10)
        palette17.setBrush(QPalette.Disabled, QPalette.WindowText, brush2)
        self.lowTempLabel_2.setPalette(palette17)
        self.lowTempLabel_2.setFont(font7)
        self.UVLabel_3 = QLabel(self.forcastWidget)
        self.UVLabel_3.setObjectName(u"UVLabel_3")
        self.UVLabel_3.setGeometry(QRect(310, 250, 51, 21))
        palette18 = QPalette()
        palette18.setBrush(QPalette.Active, QPalette.WindowText, brush10)
        palette18.setBrush(QPalette.Inactive, QPalette.WindowText, brush10)
        palette18.setBrush(QPalette.Disabled, QPalette.WindowText, brush2)
        self.UVLabel_3.setPalette(palette18)
        self.UVLabel_3.setFont(font7)
        self.UVImageLabel = QLabel(self.forcastWidget)
        self.UVImageLabel.setObjectName(u"UVImageLabel")
        self.UVImageLabel.setGeometry(QRect(270, 40, 41, 41))
        self.UVImageLabel.setPixmap(QPixmap(u":/newPrefix/sun_469-removebg-preview.png"))
        self.UVImageLabel.setScaledContents(True)
        self.weatherMain_3 = QLabel(self.forcastWidget)
        self.weatherMain_3.setObjectName(u"weatherMain_3")
        self.weatherMain_3.setGeometry(QRect(160, 230, 111, 31))
        palette19 = QPalette()
        palette19.setBrush(QPalette.Active, QPalette.WindowText, brush10)
        palette19.setBrush(QPalette.Inactive, QPalette.WindowText, brush10)
        palette19.setBrush(QPalette.Disabled, QPalette.WindowText, brush2)
        self.weatherMain_3.setPalette(palette19)
        self.weatherMain_3.setFont(font7)
        self.UVImageLabel_3 = QLabel(self.forcastWidget)
        self.UVImageLabel_3.setObjectName(u"UVImageLabel_3")
        self.UVImageLabel_3.setGeometry(QRect(270, 240, 41, 41))
        self.UVImageLabel_3.setPixmap(QPixmap(u":/newPrefix/sun_469-removebg-preview.png"))
        self.UVImageLabel_3.setScaledContents(True)
        self.percipLevelLabel_3 = QLabel(self.forcastWidget)
        self.percipLevelLabel_3.setObjectName(u"percipLevelLabel_3")
        self.percipLevelLabel_3.setGeometry(QRect(310, 210, 51, 31))
        palette20 = QPalette()
        palette20.setBrush(QPalette.Active, QPalette.WindowText, brush10)
        palette20.setBrush(QPalette.Inactive, QPalette.WindowText, brush10)
        palette20.setBrush(QPalette.Disabled, QPalette.WindowText, brush2)
        self.percipLevelLabel_3.setPalette(palette20)
        self.percipLevelLabel_3.setFont(font7)
        self.day4_border = QLabel(self.forcastWidget)
        self.day4_border.setObjectName(u"day4_border")
        self.day4_border.setGeometry(QRect(10, 300, 401, 91))
        self.day4_border.setStyleSheet(u"\n"
"border: 3px solid white;\n"
"border-radius: 15px;")
        self.highTempLabel_4 = QLabel(self.forcastWidget)
        self.highTempLabel_4.setObjectName(u"highTempLabel_4")
        self.highTempLabel_4.setGeometry(QRect(20, 330, 51, 31))
        sizePolicy1.setHeightForWidth(self.highTempLabel_4.sizePolicy().hasHeightForWidth())
        self.highTempLabel_4.setSizePolicy(sizePolicy1)
        self.highTempLabel_4.setFont(font6)
        self.UVLabel_4 = QLabel(self.forcastWidget)
        self.UVLabel_4.setObjectName(u"UVLabel_4")
        self.UVLabel_4.setGeometry(QRect(310, 350, 51, 21))
        palette21 = QPalette()
        palette21.setBrush(QPalette.Active, QPalette.WindowText, brush10)
        palette21.setBrush(QPalette.Inactive, QPalette.WindowText, brush10)
        palette21.setBrush(QPalette.Disabled, QPalette.WindowText, brush2)
        self.UVLabel_4.setPalette(palette21)
        self.UVLabel_4.setFont(font7)
        self.day1_image = QLabel(self.forcastWidget)
        self.day1_image.setObjectName(u"day1_image")
        self.day1_image.setEnabled(True)
        self.day1_image.setGeometry(QRect(100, 10, 71, 71))
        self.day1_image.setPixmap(QPixmap(u":/newPrefix/10d@2x.png"))
        self.day1_image.setScaledContents(True)
        self.day1_image.setAlignment(Qt.AlignCenter)
        self.day1_image_5 = QLabel(self.forcastWidget)
        self.day1_image_5.setObjectName(u"day1_image_5")
        self.day1_image_5.setEnabled(True)
        self.day1_image_5.setGeometry(QRect(100, 410, 71, 71))
        self.day1_image_5.setPixmap(QPixmap(u":/newPrefix/10d@2x.png"))
        self.day1_image_5.setScaledContents(True)
        self.day1_image_5.setAlignment(Qt.AlignCenter)
        self.lowTempLabel_4 = QLabel(self.forcastWidget)
        self.lowTempLabel_4.setObjectName(u"lowTempLabel_4")
        self.lowTempLabel_4.setGeometry(QRect(60, 330, 51, 31))
        palette22 = QPalette()
        palette22.setBrush(QPalette.Active, QPalette.WindowText, brush10)
        palette22.setBrush(QPalette.Inactive, QPalette.WindowText, brush10)
        palette22.setBrush(QPalette.Disabled, QPalette.WindowText, brush2)
        self.lowTempLabel_4.setPalette(palette22)
        self.lowTempLabel_4.setFont(font7)
        self.lowTempLabel_5 = QLabel(self.forcastWidget)
        self.lowTempLabel_5.setObjectName(u"lowTempLabel_5")
        self.lowTempLabel_5.setGeometry(QRect(60, 430, 51, 31))
        palette23 = QPalette()
        palette23.setBrush(QPalette.Active, QPalette.WindowText, brush10)
        palette23.setBrush(QPalette.Inactive, QPalette.WindowText, brush10)
        palette23.setBrush(QPalette.Disabled, QPalette.WindowText, brush2)
        self.lowTempLabel_5.setPalette(palette23)
        self.lowTempLabel_5.setFont(font7)
        self.percipImageLabel = QLabel(self.forcastWidget)
        self.percipImageLabel.setObjectName(u"percipImageLabel")
        self.percipImageLabel.setGeometry(QRect(270, 10, 41, 31))
        self.percipImageLabel.setPixmap(QPixmap(u":/newPrefix/5-57317_water-drop-clipart-png-transparent-png-removebg-preview.png"))
        self.percipImageLabel.setScaledContents(True)
        self.percipImageLabel_3 = QLabel(self.forcastWidget)
        self.percipImageLabel_3.setObjectName(u"percipImageLabel_3")
        self.percipImageLabel_3.setGeometry(QRect(270, 210, 41, 31))
        self.percipImageLabel_3.setPixmap(QPixmap(u":/newPrefix/5-57317_water-drop-clipart-png-transparent-png-removebg-preview.png"))
        self.percipImageLabel_3.setScaledContents(True)
        self.day4_date = QLabel(self.forcastWidget)
        self.day4_date.setObjectName(u"day4_date")
        self.day4_date.setGeometry(QRect(190, 300, 51, 31))
        self.day4_date.setFont(font8)
        self.lowTempLabel_3 = QLabel(self.forcastWidget)
        self.lowTempLabel_3.setObjectName(u"lowTempLabel_3")
        self.lowTempLabel_3.setGeometry(QRect(60, 230, 51, 31))
        palette24 = QPalette()
        palette24.setBrush(QPalette.Active, QPalette.WindowText, brush10)
        palette24.setBrush(QPalette.Inactive, QPalette.WindowText, brush10)
        palette24.setBrush(QPalette.Disabled, QPalette.WindowText, brush2)
        self.lowTempLabel_3.setPalette(palette24)
        self.lowTempLabel_3.setFont(font7)
        self.day1_date = QLabel(self.forcastWidget)
        self.day1_date.setObjectName(u"day1_date")
        self.day1_date.setGeometry(QRect(190, 0, 51, 31))
        self.day1_date.setFont(font8)
        self.UVImageLabel_4 = QLabel(self.forcastWidget)
        self.UVImageLabel_4.setObjectName(u"UVImageLabel_4")
        self.UVImageLabel_4.setGeometry(QRect(270, 340, 41, 41))
        self.UVImageLabel_4.setPixmap(QPixmap(u":/newPrefix/sun_469-removebg-preview.png"))
        self.UVImageLabel_4.setScaledContents(True)
        self.highTempLabel_2 = QLabel(self.forcastWidget)
        self.highTempLabel_2.setObjectName(u"highTempLabel_2")
        self.highTempLabel_2.setGeometry(QRect(20, 130, 51, 31))
        sizePolicy1.setHeightForWidth(self.highTempLabel_2.sizePolicy().hasHeightForWidth())
        self.highTempLabel_2.setSizePolicy(sizePolicy1)
        self.highTempLabel_2.setFont(font6)
        self.lowTempLabel = QLabel(self.forcastWidget)
        self.lowTempLabel.setObjectName(u"lowTempLabel")
        self.lowTempLabel.setGeometry(QRect(60, 30, 51, 31))
        palette25 = QPalette()
        palette25.setBrush(QPalette.Active, QPalette.WindowText, brush10)
        palette25.setBrush(QPalette.Inactive, QPalette.WindowText, brush10)
        palette25.setBrush(QPalette.Disabled, QPalette.WindowText, brush2)
        self.lowTempLabel.setPalette(palette25)
        self.lowTempLabel.setFont(font7)
        self.cityTB = QTextEdit(self.centralwidget)
        self.cityTB.setObjectName(u"cityTB")
        self.cityTB.setGeometry(QRect(20, 230, 361, 31))
        sizePolicy2 = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.cityTB.sizePolicy().hasHeightForWidth())
        self.cityTB.setSizePolicy(sizePolicy2)
        self.cityTB.setFont(font4)
        self.cityTB.setFrameShape(QFrame.NoFrame)
        self.cityTB.setFrameShadow(QFrame.Plain)
        self.cityTB.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        MainWindow.setCentralWidget(self.centralwidget)
        self.backgroundImageLabel.raise_()
        self.TitleLabel.raise_()
        self.instructionsLabel.raise_()
        self.stateComboBox.raise_()
        self.searchButton.raise_()
        self.infoLabel.raise_()
        self.forcastWidget.raise_()
        self.cityTB.raise_()

        self.retranslateUi(MainWindow)
        self.searchButton.clicked.connect(self.forcastWidget.show)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Forcasting App - Will G", None))
        self.TitleLabel.setText(QCoreApplication.translate("MainWindow", u"5 DAY\n"
"FORCAST", None))
        self.backgroundImageLabel.setText("")
        self.instructionsLabel.setText(QCoreApplication.translate("MainWindow", u"Enter your city and state below to get your\n"
"weather forcast!", None))
        self.stateComboBox.setItemText(0, QCoreApplication.translate("MainWindow", u"AL	", None))
        self.stateComboBox.setItemText(1, QCoreApplication.translate("MainWindow", u"AK", None))
        self.stateComboBox.setItemText(2, QCoreApplication.translate("MainWindow", u"AZ", None))
        self.stateComboBox.setItemText(3, QCoreApplication.translate("MainWindow", u"AR", None))
        self.stateComboBox.setItemText(4, QCoreApplication.translate("MainWindow", u"CA", None))
        self.stateComboBox.setItemText(5, QCoreApplication.translate("MainWindow", u"CO", None))
        self.stateComboBox.setItemText(6, QCoreApplication.translate("MainWindow", u"CT", None))
        self.stateComboBox.setItemText(7, QCoreApplication.translate("MainWindow", u"DE", None))
        self.stateComboBox.setItemText(8, QCoreApplication.translate("MainWindow", u"FL", None))
        self.stateComboBox.setItemText(9, QCoreApplication.translate("MainWindow", u"GA", None))
        self.stateComboBox.setItemText(10, QCoreApplication.translate("MainWindow", u"HI", None))
        self.stateComboBox.setItemText(11, QCoreApplication.translate("MainWindow", u"ID", None))
        self.stateComboBox.setItemText(12, QCoreApplication.translate("MainWindow", u"IL", None))
        self.stateComboBox.setItemText(13, QCoreApplication.translate("MainWindow", u"IN", None))
        self.stateComboBox.setItemText(14, QCoreApplication.translate("MainWindow", u"IA", None))
        self.stateComboBox.setItemText(15, QCoreApplication.translate("MainWindow", u"KS", None))
        self.stateComboBox.setItemText(16, QCoreApplication.translate("MainWindow", u"KY", None))
        self.stateComboBox.setItemText(17, QCoreApplication.translate("MainWindow", u"LA", None))
        self.stateComboBox.setItemText(18, QCoreApplication.translate("MainWindow", u"ME", None))
        self.stateComboBox.setItemText(19, QCoreApplication.translate("MainWindow", u"MD", None))
        self.stateComboBox.setItemText(20, QCoreApplication.translate("MainWindow", u"MA", None))
        self.stateComboBox.setItemText(21, QCoreApplication.translate("MainWindow", u"MI", None))
        self.stateComboBox.setItemText(22, QCoreApplication.translate("MainWindow", u"MN", None))
        self.stateComboBox.setItemText(23, QCoreApplication.translate("MainWindow", u"MS", None))
        self.stateComboBox.setItemText(24, QCoreApplication.translate("MainWindow", u"MO", None))
        self.stateComboBox.setItemText(25, QCoreApplication.translate("MainWindow", u"MT", None))
        self.stateComboBox.setItemText(26, QCoreApplication.translate("MainWindow", u"NE", None))
        self.stateComboBox.setItemText(27, QCoreApplication.translate("MainWindow", u"NV", None))
        self.stateComboBox.setItemText(28, QCoreApplication.translate("MainWindow", u"NH", None))
        self.stateComboBox.setItemText(29, QCoreApplication.translate("MainWindow", u"NJ", None))
        self.stateComboBox.setItemText(30, QCoreApplication.translate("MainWindow", u"NM", None))
        self.stateComboBox.setItemText(31, QCoreApplication.translate("MainWindow", u"NY", None))
        self.stateComboBox.setItemText(32, QCoreApplication.translate("MainWindow", u"NC", None))
        self.stateComboBox.setItemText(33, QCoreApplication.translate("MainWindow", u"ND", None))
        self.stateComboBox.setItemText(34, QCoreApplication.translate("MainWindow", u"OH", None))
        self.stateComboBox.setItemText(35, QCoreApplication.translate("MainWindow", u"OK", None))
        self.stateComboBox.setItemText(36, QCoreApplication.translate("MainWindow", u"OR", None))
        self.stateComboBox.setItemText(37, QCoreApplication.translate("MainWindow", u"PA", None))
        self.stateComboBox.setItemText(38, QCoreApplication.translate("MainWindow", u"RI", None))
        self.stateComboBox.setItemText(39, QCoreApplication.translate("MainWindow", u"SC", None))
        self.stateComboBox.setItemText(40, QCoreApplication.translate("MainWindow", u"SD", None))
        self.stateComboBox.setItemText(41, QCoreApplication.translate("MainWindow", u"TN", None))
        self.stateComboBox.setItemText(42, QCoreApplication.translate("MainWindow", u"TX", None))
        self.stateComboBox.setItemText(43, QCoreApplication.translate("MainWindow", u"UT", None))
        self.stateComboBox.setItemText(44, QCoreApplication.translate("MainWindow", u"VT", None))
        self.stateComboBox.setItemText(45, QCoreApplication.translate("MainWindow", u"VA", None))
        self.stateComboBox.setItemText(46, QCoreApplication.translate("MainWindow", u"WA", None))
        self.stateComboBox.setItemText(47, QCoreApplication.translate("MainWindow", u"WV", None))
        self.stateComboBox.setItemText(48, QCoreApplication.translate("MainWindow", u"WI", None))
        self.stateComboBox.setItemText(49, QCoreApplication.translate("MainWindow", u"WY", None))

        self.searchButton.setText(QCoreApplication.translate("MainWindow", u"Search", None))
        self.infoLabel.setText(QCoreApplication.translate("MainWindow", u"Getting forcast info for {city}, {state}", None))
        self.day3_border.setText("")
        self.highTempLabel.setText(QCoreApplication.translate("MainWindow", u"99\u00b0", None))
        self.UVImageLabel_2.setText("")
        self.percipImageLabel_2.setText("")
        self.UVLabel.setText(QCoreApplication.translate("MainWindow", u"3/10", None))
        self.percipLevelLabel.setText(QCoreApplication.translate("MainWindow", u"24%", None))
        self.UVLabel_2.setText(QCoreApplication.translate("MainWindow", u"3/10", None))
        self.percipLevelLabel_4.setText(QCoreApplication.translate("MainWindow", u"24%", None))
        self.day1_image_4.setText("")
        self.day3_date.setText(QCoreApplication.translate("MainWindow", u"Mon 23", None))
        self.day5_date.setText(QCoreApplication.translate("MainWindow", u"Wed 25", None))
        self.day1_image_3.setText("")
        self.day2_border.setText("")
        self.percipLevelLabel_5.setText(QCoreApplication.translate("MainWindow", u"24%", None))
        self.percipImageLabel_4.setText("")
        self.UVImageLabel_5.setText("")
        self.weatherMain_4.setText(QCoreApplication.translate("MainWindow", u"Partly Cloudy", None))
        self.day2_date.setText(QCoreApplication.translate("MainWindow", u"Sun 22", None))
        self.weatherMain.setText(QCoreApplication.translate("MainWindow", u"Partly Cloudy", None))
        self.percipLevelLabel_2.setText(QCoreApplication.translate("MainWindow", u"24%", None))
        self.day1_border.setText("")
        self.day5_border.setText("")
        self.UVLabel_5.setText(QCoreApplication.translate("MainWindow", u"3/10", None))
        self.percipImageLabel_5.setText("")
        self.weatherMain_2.setText(QCoreApplication.translate("MainWindow", u"Partly Cloudy", None))
        self.weatherMain_5.setText(QCoreApplication.translate("MainWindow", u"Partly Cloudy", None))
        self.day1_image_2.setText("")
        self.highTempLabel_5.setText(QCoreApplication.translate("MainWindow", u"99\u00b0", None))
        self.highTempLabel_3.setText(QCoreApplication.translate("MainWindow", u"99\u00b0", None))
        self.lowTempLabel_2.setText(QCoreApplication.translate("MainWindow", u"/66\u00b0", None))
        self.UVLabel_3.setText(QCoreApplication.translate("MainWindow", u"3/10", None))
        self.UVImageLabel.setText("")
        self.weatherMain_3.setText(QCoreApplication.translate("MainWindow", u"Partly Cloudy", None))
        self.UVImageLabel_3.setText("")
        self.percipLevelLabel_3.setText(QCoreApplication.translate("MainWindow", u"24%", None))
        self.day4_border.setText("")
        self.highTempLabel_4.setText(QCoreApplication.translate("MainWindow", u"99\u00b0", None))
        self.UVLabel_4.setText(QCoreApplication.translate("MainWindow", u"3/10", None))
        self.day1_image.setText("")
        self.day1_image_5.setText("")
        self.lowTempLabel_4.setText(QCoreApplication.translate("MainWindow", u"/66\u00b0", None))
        self.lowTempLabel_5.setText(QCoreApplication.translate("MainWindow", u"/66\u00b0", None))
        self.percipImageLabel.setText("")
        self.percipImageLabel_3.setText("")
        self.day4_date.setText(QCoreApplication.translate("MainWindow", u"Tue 24", None))
        self.lowTempLabel_3.setText(QCoreApplication.translate("MainWindow", u"/66\u00b0", None))
        self.day1_date.setText(QCoreApplication.translate("MainWindow", u"Sat 21", None))
        self.UVImageLabel_4.setText("")
        self.highTempLabel_2.setText(QCoreApplication.translate("MainWindow", u"99\u00b0", None))
        self.lowTempLabel.setText(QCoreApplication.translate("MainWindow", u"/66\u00b0", None))
        self.cityTB.setPlaceholderText(QCoreApplication.translate("MainWindow", u"City", None))
    # retranslateUi

